version: '3'
services:
  sqlite3:
    container_name: my-sqlite-container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - sqlite-data:/mydatabase
    ports:
      - "5432:5432"
    restart: always

volumes:
  sqlite-data: